apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-ENVIRONMENT-BUILD_NUMBER
  labels:
    app:  web-app-ENVIRONMENT-BUILD_NUMBER
    version: "BUILD_NUMBER"
spec:
  replicas: 3
  selector:
    matchLabels:
      versions: "BUILD_NUMBER"
  template:
    metadata:
      labels:
        app: web-app-ENVIRONMENT-BUILD_NUMBER
        version: "BUILD_NUMBER"
    spec:
      containers:
      - name: web-app-ENVIRONMENT-BUILD_NUMBER
        image: IMAGE
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
