apiVersion: v1
kind: Service
metadata:
  name: web-app-ENVIRONMENT-svc-BUILD_NUMBER
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: web-app
    version: "BUILD_NUMBER"
