apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Environment=ENVIRONMENT"

  name: web-app-ENVIRONMENT-svc-BUILD_NUMBER
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
      name: http
  selector:
    app: web-app
    version: "BUILD_NUMBER"
